type Movie @key(fields: "id") {
	id: ID!
	title: String!
	year: Int!
	rating: Float
}

input MovieWhereUniqueInput {
	id: ID!
}

input CreateMovieInput {
	title: String!
	year: Int!
	rating: Float
}

type Query {
	movie(where: MovieWhereUniqueInput!): Movie
	movies: [Movie!]
}

type Mutation {
	createMovie(input: CreateMovieInput!): Movie!
}
