name: Setup environment
description: Composite action for Node.js and dependencies installation
inputs:
  node-version:
    description: Node.js version to use
    required: true
    default: "24"

runs:
  using: composite
  steps:
    - name: Cancel Previous Run
      uses: styfle/cancel-workflow-action@0.12.1
      continue-on-error: true
      with:
        access_token: ${{ github.token }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable Corepack
      shell: bash
      run: |
        npm uninstall -g yarn || true
        corepack enable

    - name: Get yarn cache directory
      id: yarn-cache
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache yarn
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: yarn-cache-${{ runner.os }}-

    - name: Cache turbo
      uses: actions/cache@v3
      with:
        path: .turbo
        key: turbo-cache-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-cache-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: yarn install
      working-directory: ${{ inputs.workingDirectory }}
