projects:
  examples/apollo:
    schema:
      - "examples/apollo/src/modules/**/*.gql"
    include:
      - "examples/apollo/src/**/*.gql"

  examples/apollo-ws:
    schema:
      - "examples/apollo-ws/src/modules/**/*.gql"
    include:
      - "examples/apollo-ws/src/**/*.gql"

  examples/cloudflare:
    schema:
      - "examples/cloudflare/src/modules/**/*.gql"
    include:
      - "examples/cloudflare/src/**/*.gql"

  examples/cloudflare-ws:
    schema:
      - "examples/cloudflare-ws/src/modules/**/*.gql"
    include:
      - "examples/cloudflare-ws/src/**/*.gql"

  examples/directives:
    schema:
      - "examples/directives/src/modules/**/*.gql"
    include:
      - "examples/directives/src/**/*.gql"

  examples/prisma:
    schema:
      - "examples/apollo/src/modules/**/*.gql"
    include:
      - "examples/apollo/src/**/*.gql"

  examples/scalars:
    schema:
      - "examples/scalars/src/modules/**/*.gql"
    include:
      - "examples/scalars/src/**/*.gql"

  examples/yoga:
    schema:
      - "examples/yoga/src/modules/**/*.gql"
    include:
      - "examples/yoga/src/**/*.gql"

  examples/yoga-ws:
    schema:
      - "examples/yoga-ws/src/modules/**/*.gql"
    include:
      - "examples/yoga-ws/src/**/*.gql"