projects:
  examples/apollo-ws:
    schema:
      - "examples/apollo-ws/src/modules/**/*.gql"
    include:
      - "examples/apollo-ws/src/**/*.gql"

  examples/apollo:
    schema:
      - "examples/apollo/src/modules/**/*.gql"
    include:
      - "examples/apollo/src/**/*.gql"

  examples/auth:
    schema:
      - "examples/auth/src/modules/**/*.gql"
    include:
      - "examples/auth/src/**/*.gql"

  examples/cache-advanced:
    schema:
      - "examples/cache-advanced/src/modules/**/*.gql"
    include:
      - "examples/cache-advanced/src/**/*.gql"

  examples/cache:
    schema:
      - "examples/cache/src/modules/**/*.gql"
    include:
      - "examples/cache/src/**/*.gql"

  examples/cloudflare-ws:
    schema:
      - "examples/cloudflare-ws/src/modules/**/*.gql"
    include:
      - "examples/cloudflare-ws/src/**/*.gql"

  examples/cloudflare:
    schema:
      - "examples/cloudflare/src/modules/**/*.gql"
    include:
      - "examples/cloudflare/src/**/*.gql"

  examples/complexity:
    schema:
      - "examples/complexity/src/modules/**/*.gql"
    include:
      - "examples/complexity/src/**/*.gql"

  examples/context-store:
    schema:
      - "examples/context-store/src/modules/**/*.gql"
    include:
      - "examples/context-store/src/**/*.gql"

  examples/directives:
    schema:
      - "examples/directives/src/modules/**/*.gql"
    include:
      - "examples/directives/src/**/*.gql"

  examples/prisma:
    schema:
      - "examples/prisma/src/modules/**/*.gql"
    include:
      - "examples/prisma/src/**/*.gql"

  examples/relay-pagination:
    schema:
      - "examples/relay-pagination/src/modules/**/*.gql"
    include:
      - "examples/relay-pagination/src/**/*.gql"

  examples/scalars:
    schema:
      - "examples/scalars/src/modules/**/*.gql"
    include:
      - "examples/scalars/src/**/*.gql"

  examples/unions-interfaces:
    schema:
      - "examples/unions-interfaces/src/modules/**/*.gql"
    include:
      - "examples/unions-interfaces/src/**/*.gql"

  examples/yoga-sse:
    schema:
      - "examples/yoga-sse/src/modules/**/*.gql"
    include:
      - "examples/yoga-sse/src/**/*.gql"

  examples/yoga-ws:
    schema:
      - "examples/yoga-ws/src/modules/**/*.gql"
    include:
      - "examples/yoga-ws/src/**/*.gql"

  examples/yoga:
    schema:
      - "examples/yoga/src/modules/**/*.gql"
    include:
      - "examples/yoga/src/**/*.gql"

