compressionLevel: mixed

enableColors: true

enableGlobalCache: false

npmAuthToken: "${NPM_TOKEN-}"

packageExtensions:
  typedoc@*:
    peerDependencies:
      typedoc-plugin-markdown: "*"
      typedoc-docusaurus-theme: "*"
  typedoc-docusaurus-theme@*:
    peerDependencies:
      typedoc: "*"

preferInteractive: true
