compressionLevel: mixed

enableColors: true

enableGlobalCache: false

npmAuthToken: "${NPM_TOKEN-}"

packageExtensions:
  "@docusaurus/core@*":
    peerDependencies:
      "@docusaurus/faster": "*"
  "typedoc-docusaurus-theme@*":
    peerDependencies:
      "typedoc": "*"

preferInteractive: true

changesetBaseRefs: ["HEAD"]

catalogs:
  prod:
    "graphql-ws": "^6.0.8"
    "react-dom": "^19.2.4"
    "react": "^19.2.4"
  dev:
    "@types/node": "^22.19.13"
    "@types/react": "^19.2.14"
    "@types/react-dom": "^19.2.3"
    "@types/ws": "^8.18.1"
    "graphql-scalars": "^1.25.0"
    "graphql-tag": "^2.12.6"
    "graphql-yoga": "^5.20.0"
    "graphql": "^16.6.0"
    "typescript": "^5.9.3"
    "ws": "^8.20.0"
