compressionLevel: mixed

enableColors: true

enableGlobalCache: false

npmAuthToken: "${NPM_TOKEN-}"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs

packageExtensions:
  typedoc@*:
   peerDependencies:
     typedoc-plugin-markdown: "*"