compressionLevel: mixed

enableColors: true

enableGlobalCache: false

npmAuthToken: "${NPM_TOKEN-}"

preferInteractive: true

packageExtensions:
  typedoc@*:
   peerDependencies:
     typedoc-plugin-markdown: "*"
