packageExtensions:
  "@envelop/core@*":
    dependencies:
      tslib: "*"
  "@envelop/types@*":
    dependencies:
      tslib: "*"
  "@envelop/validation-cache@*":
    dependencies:
      tslib: "*"
  "@envelop/parser-cache@*":
    dependencies:
      tslib: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
