compressionLevel: mixed

enableColors: true

enableGlobalCache: false

npmAuthToken: "${NPM_TOKEN-}"

packageExtensions:
  typedoc@*:
    peerDependencies:
      typedoc-plugin-markdown: "*"

preferInteractive: true
