catalogs:
  dev:
    "@graphql-codegen/cli": ^7.0.0
    "@graphql-codegen/client-preset": ^6.0.0
    "@types/node": ^22.19.17
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
    "@types/ws": ^8.18.1
    graphql: ^17.0.0
    graphql-scalars: ^1.25.0
    graphql-yoga: ^5.21.0
    typescript: ^6.0.0
    ws: ^8.20.0
  prod:
    graphql-ws: ^6.0.8
    react: ^19.2.4
    react-dom: ^19.2.4

changesetBaseRefs:
  - HEAD

compressionLevel: 0

enableColors: true

enableScripts: false

npmAuthToken: "${NPM_TOKEN-}"

npmMinimalAgeGate: 3d

packageExtensions:
  "@changesets/cli@*":
    peerDependencies:
      "@baeta/changelog": "*"
  typedoc-docusaurus-theme@*:
    peerDependencies:
      typedoc: "*"

preferInteractive: true
