compressionLevel: mixed

enableColors: true

enableGlobalCache: false

npmAuthToken: "${NPM_TOKEN-}"

packageExtensions:
  "@miniflare/r2@*":
    peerDependencies:
      "@miniflare/core": "*"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
