compressionLevel: mixed

enableColors: true

enableGlobalCache: false

npmAuthToken: "${NPM_TOKEN-}"

packageExtensions:
  "@docusaurus/core@*":
    peerDependencies:
      "@docusaurus/faster": "*"
  typedoc-docusaurus-theme@*:
    peerDependencies:
      typedoc: "*"

preferInteractive: true

changesetBaseRefs: ["HEAD"]
