catalogs:
  dev:
    "@graphql-codegen/cli": ^6.2.1
    "@graphql-codegen/client-preset": ^5.2.4
    "@types/node": ^22.19.13
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
    "@types/ws": ^8.18.1
    graphql: ^16.6.0
    graphql-scalars: ^1.25.0
    graphql-yoga: ^5.20.0
    typescript: ^5.9.3
    ws: ^8.20.0
  prod:
    graphql-ws: ^6.0.8
    react: ^19.2.4
    react-dom: ^19.2.4

changesetBaseRefs:
  - HEAD

compressionLevel: mixed

enableColors: true

enableScripts: false

npmAuthToken: "${NPM_TOKEN-}"

npmMinimalAgeGate: 3d

packageExtensions:
  typedoc-docusaurus-theme@*:
    peerDependencies:
      typedoc: "*"

preferInteractive: true
