version: '3.8'

services:
  redis-test:
    image: redis:7-alpine
    ports:
      - "65535:6379"
    command: redis-server --save "" --appendonly no  # Disable persistence for tests
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30 