services:
  redis-test:
    image: redis:7-alpine
    ports:
      - "65535:6379"
    command: redis-server --save "" --appendonly no # Disable persistence for tests
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  valkey-test:
    image: valkey/valkey:8-alpine
    ports:
      - "65534:6379"
    command: valkey-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  serverless-redis-http:
    ports:
      - "60080:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis-test:6379/1"
