/* This file was generated by baeta. Do not edit it directly. */

/* eslint-disable */

import "./baeta-directives/directives.baeta";

import "./user/resolvers";

import "./user-photos/resolvers";

import "./baeta-directives/directives.baeta";

import {getBaetaDirectivesModule} from "./baeta-directives/typedef";

import {getBaetaPaginationModule} from "./baeta-pagination/typedef";

import {getUserPhotosModule} from "./user-photos/typedef";

import {getUserModule} from "./user/typedef";

export const modules = [getBaetaDirectivesModule(), getBaetaPaginationModule(), getUserPhotosModule(), getUserModule()];
