/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

import type { ModuleCompilerFactory } from "@baeta/core/sdk";
import type { Ctx, Info } from "./types.ts"
import type { BaetaModuleTypes as UserPhotosModuleTypes } from "./user-photos/typedef.ts"
import type { BaetaModuleTypes as UserModuleTypes } from "./user/typedef.ts"
import userPhotos from "./user-photos/index.ts"
import user from "./user/index.ts"

export default [
    userPhotos satisfies ModuleCompilerFactory<Ctx, Info, UserPhotosModuleTypes["Factories"]>,
    user satisfies ModuleCompilerFactory<Ctx, Info, UserModuleTypes["Factories"]>
];