/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

export type Or<A, B> = void extends A ? B : A;

export type Maybe<T> = T | null;

export type BaseScalars = {
  ID: string;
  Int: number;
  Float: number;
  String: string;
  Boolean: boolean;
};

export interface BaseObjectTypes {
  UserPhoto: unknown;
  User: unknown;
  Query: unknown;
};