/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

import type * as BaetaTypes from "./types.ts";
import type * as BaetaUserTypes from "../modules/types.ts";

type Result<T> = T | PromiseLike<T>;

export type ProductEntityRepresentation = { __typename: "Product" } & ({ id: BaetaTypes.Scalars["ID"] })

export type ProductEntityHandler = (representation: ProductEntityRepresentation, ctx: BaetaUserTypes.Ctx, info: BaetaUserTypes.Info) => Result<BaetaTypes.Product & {__typename: "Product"} | null>

export type EntityRepresentation = ProductEntityRepresentation;

export type EntityHandlerMap = { "Product": ProductEntityHandler };