/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import { getBaetaDirectivesModule } from "./typedef.ts";

import "./directives.baeta";

export const baetaDirectivesModule = getBaetaDirectivesModule();
