/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import baetaDirectives from "./baeta-directives/index.ts"
import baetaPagination from "./baeta-pagination/index.ts"
import scalars from "./scalars/index.ts"
import userPhotosPages from "./user-photos-pages/index.ts"
import userPhotos from "./user-photos/index.ts"
import user from "./user/index.ts"

export default [baetaDirectives, baetaPagination, scalars, userPhotosPages, userPhotos, user];