import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createApplication } from '@baeta/core';
import { execute } from '@baeta/e2e-shared/execute';
import test from '@baeta/testing';
import { graphql } from './src/__generated__/gql/index.ts';
import modules from './src/modules/index.ts';

const { schema } = createApplication({ modules });

const MovieQuery = graphql(`
	query MovieQuery($where: MovieWhereUniqueInput!) {
		movie(where: $where) {
			id
			title
		}
	}
`);

let cachedGitignorePromise: Promise<string> | null = null;
async function readGitignore() {
	if (cachedGitignorePromise) {
		return await cachedGitignorePromise;
	}
	const fixturePath = resolve(import.meta.dirname, '.');
	cachedGitignorePromise = readFile(resolve(fixturePath, '.gitignore'), 'utf-8');
	return await cachedGitignorePromise;
}

test('gitignore plugin creates .gitignore with generated paths', async (t) => {
	const gitignore = await readGitignore();
	t.true(gitignore.includes('# Generated by Baeta - Begin'));
	t.true(gitignore.includes('# Generated by Baeta - End'));
});

test('.gitignore contains generated type files', async (t) => {
	const gitignore = await readGitignore();
	t.true(gitignore.includes('__generated__/types.ts'));
	t.true(gitignore.includes('__generated__/utility.ts'));
});

test('.gitignore contains modules index', async (t) => {
	const gitignore = await readGitignore();
	t.true(gitignore.includes('src/modules/index.ts'));
});

test('.gitignore contains typedef pattern', async (t) => {
	const gitignore = await readGitignore();
	t.true(gitignore.includes('typedef.ts'));
});

test('schema still works with gitignore plugin', async (t) => {
	const result = await execute({
		schema,
		document: MovieQuery,
		variableValues: { where: { id: '1' } },
		contextValue: { appVersion: '1.0.0' },
	});
	t.falsy(result.errors);
	t.is(result.data?.movie?.id, '1');
});
