import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createApplication } from '@baeta/core';
import { execute } from '@baeta/e2e-shared/execute';
import test from '@baeta/testing';
import { graphql } from './src/__generated__/gql/index.ts';
import modules from './src/modules/index.ts';

const fixturePath = resolve(import.meta.dirname, '.');

const { schema } = createApplication({ modules });

const MovieQuery = graphql(`
	query MovieQuery($where: MovieWhereUniqueInput!) {
		movie(where: $where) {
			id
			title
		}
	}
`);

function readGitignore() {
	return readFileSync(resolve(fixturePath, '.gitignore'), 'utf-8');
}

test.serial('gitignore plugin creates .gitignore with generated paths', (t) => {
	const gitignore = readGitignore();

	t.true(gitignore.includes('# Generated by Baeta - Begin'));
	t.true(gitignore.includes('# Generated by Baeta - End'));
});

test.serial('.gitignore contains generated type files', (t) => {
	const gitignore = readGitignore();

	t.true(gitignore.includes('__generated__/types.ts'));
	t.true(gitignore.includes('__generated__/utility.ts'));
});

test.serial('.gitignore contains modules index', (t) => {
	const gitignore = readGitignore();

	t.true(gitignore.includes('src/modules/index.ts'));
});

test.serial('.gitignore contains typedef pattern', (t) => {
	const gitignore = readGitignore();

	t.true(gitignore.includes('typedef.ts'));
});

test.serial('schema still works with gitignore plugin', async (t) => {
	const result = await execute({
		schema,
		document: MovieQuery,
		variableValues: { where: { id: '1' } },
		contextValue: { appVersion: '1.0.0' },
	});

	t.falsy(result.errors);
	t.is(result.data?.movie?.id, '1');
});
