import fs from 'node:fs/promises';
import { dirname, extname } from '@baeta/util-path';

/**
 * Options for generated files.
 */
export interface FileOptions {
	/**
	 * Disable generation notice at the beginning of the file.
	 * @defaultValue false
	 */
	disableGenerationNoticeHeader?: boolean;

	/**
	 * Enable lint disabling headers at the beginning of the file.
	 * Can be either a boolean to enable all supported lint headers or an object to enable specific ones.
	 * @defaultValue false
	 */
	enableLintHeaders?:
		| boolean
		| {
				/**
				 * Enable oxlint comment at the beginning of the file.
				 * @defaultValue false
				 */
				oxlint?: boolean;
				/**
				 * Enable eslint-disable comment at the beginning of the file.
				 * @defaultValue false
				 */
				eslint?: boolean;
				/**
				 * Enable biome v1 comment at the beginning of the file.
				 * @defaultValue false
				 */
				biomeV1?: boolean;
				/**
				 * Enable biome v2 comment at the beginning of the file.
				 * @defaultValue false
				 */
				biomeV2?: boolean;
		  };

	/**
	 * Disallow overwriting the file.
	 * @defaultValue false
	 */
	disableOverwrite?: boolean;

	/**
	 * Add custom header at the beginning of the file.
	 */
	addHeader?: (name: string, content: string, tag: string) => string;

	/**
	 * Edit the content of the file before writing it.
	 */
	transformContent?: (name: string, content: string, tag: string) => string | Promise<string>;
}

export class File {
	persisted = false;
	readonly filename: string;
	readonly content: string;
	readonly tag: string;
	readonly options?: FileOptions;

	constructor(filename: string, content: string, tag: string, options?: FileOptions) {
		this.filename = filename;
		this.content = content;
		this.tag = tag;
		this.options = options;
	}

	write = async () => {
		if (this.persisted) {
			return;
		}
		this.persisted = true;

		if (this.options?.disableOverwrite === true) {
			const exists = await fs
				.stat(this.filename)
				.then((res) => res.isFile())
				.catch(() => false);
			if (exists) return;
		}

		const dir = dirname(this.filename);
		await fs.mkdir(dir, { recursive: true });

		const content = await this.buildContent();

		return await fs.writeFile(this.filename, content, 'utf-8');
	};

	unlink = async () => {
		this.persisted = false;
		return await fs.unlink(this.filename);
	};

	protected async buildContent() {
		const content = this.buildHeader() + this.content;

		if (this.options?.transformContent) {
			return await this.options.transformContent(this.filename, content, this.tag);
		}

		return content;
	}

	protected buildHeader() {
		const headerItems: string[] = [];

		if (this.options?.disableGenerationNoticeHeader !== true) {
			const comment = this.createComment(
				'This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator.',
			);
			headerItems.push(comment);
		}

		if (
			this.options?.enableLintHeaders === true ||
			typeof this.options?.enableLintHeaders === 'object'
		) {
			if (
				this.options?.enableLintHeaders === true ||
				this.options?.enableLintHeaders?.eslint !== false
			) {
				const comment = this.createComment('eslint-disable');
				headerItems.push(comment);
			}
			if (
				this.options?.enableLintHeaders === true ||
				this.options?.enableLintHeaders?.oxlint !== false
			) {
				const comment = this.createComment('oxlint-disable');
				headerItems.push(comment);
			}
			if (
				this.options?.enableLintHeaders === true ||
				this.options?.enableLintHeaders?.biomeV1 !== false
			) {
				const comment = this.createComment('@biome-ignore-all: generated file');
				headerItems.push(comment);
			}
			if (
				this.options?.enableLintHeaders === true ||
				this.options?.enableLintHeaders?.biomeV2 !== false
			) {
				const comment = this.createComment('biome-ignore-all lint: generated file');
				headerItems.push(comment);
			}
		}

		if (this.options?.addHeader) {
			const customHeader = this.options.addHeader(this.filename, this.content, this.tag);
			headerItems.push(customHeader);
		}

		if (headerItems.length === 0) {
			return '';
		}

		return `${headerItems.join('\n')}\n\n`;
	}

	protected createComment(comment: string) {
		const extension = extname(this.filename);
		if (['.gql', '.graphql'].includes(extension)) {
			return `# ${comment}`;
		}
		return `/* ${comment} */`;
	}
}
