/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */

import "./user/resolvers";

import {getUserModule} from "./user/typedef";

export const modules = [getUserModule()];
