/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */
/* biome-ignore-all lint: generated file */

import type { ModuleCompilerFactory } from "@baeta/core/sdk";
import type { Ctx, Info } from "./types.ts"
import type { BaetaModuleTypes as BaetaFederationModuleTypes } from "./baeta-federation/typedef.ts"
import type { BaetaModuleTypes as ProductModuleTypes } from "./product/typedef.ts"
import type { BaetaModuleTypes as UserModuleTypes } from "./user/typedef.ts"
import baetaFederation from "./baeta-federation/index.ts"
import product from "./product/index.ts"
import user from "./user/index.ts"

export default [
    baetaFederation satisfies ModuleCompilerFactory<Ctx, Info, BaetaFederationModuleTypes["Factories"]>,
    product satisfies ModuleCompilerFactory<Ctx, Info, ProductModuleTypes["Factories"]>,
    user satisfies ModuleCompilerFactory<Ctx, Info, UserModuleTypes["Factories"]>
];