/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */
/* biome-ignore-all lint: generated file */

import type {Ctx, Info} from "../modules/types.ts";
import * as Types from "./types.ts";

type Result<T> = T | PromiseLike<T>;

export type UserEntityRepresentation = { __typename: "User" } & ({ id: Types.Scalars["ID"] })

export type UserEntityHandler = (representation: UserEntityRepresentation, ctx: Ctx, info: Info) => Result<Types.User & {__typename: "User"} | null>

export type EntityRepresentation = UserEntityRepresentation;

export type EntityHandlerMap = { "User": UserEntityHandler };