/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */
/* biome-ignore-all lint: generated file */

import type * as BaetaTypes from "./types.ts";
import type * as BaetaUserTypes from "../modules/types.ts";

type Result<T> = T | PromiseLike<T>;

export type UserEntityRepresentation = { __typename: "User" } & ({ id: BaetaTypes.Scalars["ID"] })

export type UserEntityHandler = (representation: UserEntityRepresentation, ctx: BaetaUserTypes.Ctx, info: BaetaUserTypes.Info) => Result<BaetaTypes.User & {__typename: "User"} | null>

export type EntityRepresentation = UserEntityRepresentation;

export type EntityHandlerMap = { "User": UserEntityHandler };