/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

import type * as BaetaUtility from "./utility.ts";
import type * as BaetaOverrides from "../modules/types.ts";

export type Scalars = BaetaOverrides.Scalars;

export type Query = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Query"], {
  _service: _Service
  _entities: Array<_Entity | null>
  user: User | null
  users: Array<User> | null
}>

export type _Service = BaetaUtility.Or<BaetaOverrides.ObjectTypes["_Service"], {
  sdl: Scalars["String"]
}>

export type User = BaetaUtility.Or<BaetaOverrides.ObjectTypes["User"], {
  id: Scalars["ID"]
  email: Scalars["String"]
  lastName: Scalars["String"]
  profile: Scalars["String"] | null
  givenName: Scalars["String"] | null
}>

export type _ServiceSdlArgs = {
};

export type QueryServiceArgs = {
};

export type QueryEntitiesArgs = {
  representations: Array<Scalars["_Any"]>
};

export type QueryUserArgs = {
  where: UserWhereUniqueInput
};

export type QueryUsersArgs = {
};

export type UserIdArgs = {
};

export type UserEmailArgs = {
};

export type UserLastNameArgs = {
};

export type UserProfileArgs = {
};

export type UserGivenNameArgs = {
};

export type UserWhereUniqueInput = {
  id: Scalars["ID"]
};

export type _Entity = User & {__typename: "User"}