import fs from "fs/promises";
import { dirname, extname } from "path";

export class File {
  persisted = false;

  constructor(
    public filename: string,
    public content: string,
    public tag: string
  ) {}

  write = async () => {
    if (this.persisted) {
      return;
    }
    this.persisted = true;

    const dir = dirname(this.filename);
    await fs.mkdir(dir, { recursive: true });
    return fs.writeFile(this.filename, this.buildContent(), "utf-8");
  };

  unlink = async () => {
    this.persisted = false;
    return fs.unlink(this.filename);
  };

  private buildContent() {
    const header = this.createComment(
      `This file was generated by baeta. Do not edit it directly.`
    );
    return header + "\n\n" + this.content;
  }

  private createComment(comment: string) {
    const ext = extname(this.filename);

    if ([".gql", ".graphql"].includes(ext)) {
      return `# ${comment}`;
    }

    return `/* ${comment} */`;
  }
}
