/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import { getBaetaPaginationModule } from "./typedef.ts";

export const baetaPaginationModule = getBaetaPaginationModule();
