/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */

import "./baeta-directives/directives.baeta";

import "./scalars/scalars.resolvers";

import "./user/user.mutations";

import "./user/user.queries";

import "./user/user.subscriptions";

import "./user-photos/user-photos.resolvers";

import {getBaetaDirectivesModule} from "./baeta-directives/typedef";

import {getScalarsModule} from "./scalars/typedef";

import {getUserPhotosModule} from "./user-photos/typedef";

import {getUserModule} from "./user/typedef";

export const modules = [getBaetaDirectivesModule(), getScalarsModule(), getUserPhotosModule(), getUserModule()];
