/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

import type { ModuleCompilerFactory } from "@baeta/core/sdk";
import type { Ctx, Info } from "./types.ts"
import type { BaetaModuleTypes as BaetaDirectivesModuleTypes } from "./baeta-directives/typedef.ts"
import type { BaetaModuleTypes as ScalarsModuleTypes } from "./scalars/typedef.ts"
import type { BaetaModuleTypes as UserPhotosModuleTypes } from "./user-photos/typedef.ts"
import type { BaetaModuleTypes as UserModuleTypes } from "./user/typedef.ts"
import baetaDirectives from "./baeta-directives/index.ts"
import scalars from "./scalars/index.ts"
import userPhotos from "./user-photos/index.ts"
import user from "./user/index.ts"

export default [
    baetaDirectives satisfies ModuleCompilerFactory<Ctx, Info, BaetaDirectivesModuleTypes["Factories"]>,
    scalars satisfies ModuleCompilerFactory<Ctx, Info, ScalarsModuleTypes["Factories"]>,
    userPhotos satisfies ModuleCompilerFactory<Ctx, Info, UserPhotosModuleTypes["Factories"]>,
    user satisfies ModuleCompilerFactory<Ctx, Info, UserModuleTypes["Factories"]>
];