/* This file was generated by baeta. Do not edit it directly. */

/* eslint-disable */
/* prettier-ignore */

import { definitions } from "@baeta/directives";
import { getDirectivesModule } from './typedef';

export const directiveModule = getDirectivesModule();
definitions.forEach((definition) => directiveModule.$directive(definition.directive));
