/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

export default "\nextend schema @link(url: \"https://specs.apollo.dev/federation/v2.9\", import: [\"@key\"])\n\ntype Product @key(fields: \"id\") {\n  id: ID!\n  name: String!\n  price: Float!\n  owner: User\n}\n\ntype Query {\n  product(id: ID!): Product\n}\n\ntype User @key(fields: \"id\", resolvable: false) {\n  id: ID!\n}\n";
