import { relative } from '@baeta/util-path';

interface PrintHandlersStarterOptions {
	typesDir: string;
	federationRootDir: string;
	extension: '' | '.ts' | '.js';
}

export function printHandlersStarter(options: PrintHandlersStarterOptions) {
	const relativeTypesDir = relative(options.federationRootDir, options.typesDir);
	return [
		'/**',
		'* Register your reference resolvers for federation entities in this file.',
		'* This file is generated by Baeta, but it will not be overwritten once created,',
		"* so it's safe to edit it directly.",
		'*/',
		'',
		`import type { EntityHandlerMap } from "${relativeTypesDir}/federation.ts";`,
		'',
		'const entityHandlersMap: EntityHandlerMap = {',
		'',
		'};',
		'',
		'export default entityHandlersMap;',
	].join('\n');
}
