/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

export default `
extend schema @link(url: "https://specs.apollo.dev/federation/v2.9", import: ["@key"])

type User @key(fields: "id") {
  id: ID!
  email: String!
  lastName: String!
  profile: String
  givenName: String
}

input UserWhereUniqueInput {
  id: ID!
}

type Query {
  user(where: UserWhereUniqueInput!): User
  users: [User!]
}
`;