/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

import * as BaetaFederation from "@baeta/federation";
import type * as FederationTypes from "../../__generated__/federation.ts";
import federationSDL from "./federation-sdl.ts";
import { BaetaFederationModule } from "./typedef.ts";
import handlersMap from "./entity-handlers.ts"

export default BaetaFederationModule.$schema({
  Query: BaetaFederationModule.Query.$fields({
    _entities: BaetaFederationModule.Query._entities.resolve((params) => {
      const representations = params.args.representations as FederationTypes.EntityRepresentation[];
      return BaetaFederation.resolveEntities(representations, handlersMap satisfies FederationTypes.EntityHandlerMap, params.ctx, params.info);
    }),
    _service: BaetaFederationModule.Query._service.resolve(() => {
      return { sdl: federationSDL };
    }),
  }),
  _Service: BaetaFederationModule._Service.$fields({
    sdl: BaetaFederationModule._Service.sdl.key('sdl'),
  }),
  _Any: BaetaFederation.createFederationScalar('json', '_Any'),
  FieldSet: BaetaFederation.createFederationScalar('string', 'FieldSet')
});