/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */

import "./comic/comic.resolvers";

import "./media/media.resolvers";

import {getComicModule} from "./comic/typedef";

import {getMediaModule} from "./media/typedef";

export const modules = [getComicModule(), getMediaModule()];
