/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */

import "./comic/comic.resolvers.ts";

import "./media/media.resolvers.ts";

import {getComicModule} from "./comic/typedef.ts";

import {getMediaModule} from "./media/typedef.ts";

export const modules = [getComicModule(), getMediaModule()];
