/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */
/* biome-ignore-all lint: generated file */

import comic from "./comic/index.ts"
import media from "./media/index.ts"

export default [comic, media];