/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */

import "./baeta-directives/directives.baeta";

import "./custom-input-directive/custom-input-directive.resolvers";

import "./custom-native-directive/custon-native-directive.resolvers";

import "./user/user.resolvers";

import {getBaetaDirectivesModule} from "./baeta-directives/typedef";

import {getCustomInputDirectiveModule} from "./custom-input-directive/typedef";

import {getCustomNativeDirectiveModule} from "./custom-native-directive/typedef";

import {getUserModule} from "./user/typedef";

export const modules = [getBaetaDirectivesModule(), getCustomInputDirectiveModule(), getCustomNativeDirectiveModule(), getUserModule()];
