/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import "./baeta-directives/directives.baeta.ts";

import "./custom-input-directive/custom-input-directive.resolvers.ts";

import "./custom-native-directive/custon-native-directive.resolvers.ts";

import "./user/user.resolvers.ts";

import {getBaetaDirectivesModule} from "./baeta-directives/typedef.ts";

import {getCustomInputDirectiveModule} from "./custom-input-directive/typedef.ts";

import {getCustomNativeDirectiveModule} from "./custom-native-directive/typedef.ts";

import {getUserModule} from "./user/typedef.ts";

export const modules = [getBaetaDirectivesModule(), getCustomInputDirectiveModule(), getCustomNativeDirectiveModule(), getUserModule()];
