name = "jolly"
main = "dist/app.mjs"
compatibility_date = "2023-02-24"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[durable_objects]
bindings = [{name = "WS_CONNECTIONS", class_name = "WsConnections"}]

[[ d1_databases ]]
binding = "SUBSCRIPTIONS"
database_name = "SUBSCRIPTIONS"
database_id = "7a6f91c0-9455-402f-ab6a-508d140da0e1"
migrations_dir = "./migrations"

[[migrations]]
new_classes = ["WsConnections"]
tag = "v1"
