type User {
  id: ID!
  name: String!
  birthday: DateTime
}

input UserWhereUnique @constraints(minFields: 1, maxFields: 1) {
  id: ID
  email: String @trim @lower @validString(format: EMAIL)
}

type Query {
  user(where: UserWhereUnique): User
}
