/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

import type * as BaetaUtility from "./utility.ts";
import type * as BaetaOverrides from "../modules/types.ts";

export type Scalars = BaetaOverrides.Scalars;

export type Query = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Query"], {
  user: User | null
}>

export type User = BaetaUtility.Or<BaetaOverrides.ObjectTypes["User"], {
  id: Scalars["UUID"]
  email: Scalars["String"]
  birthday: Scalars["DateTime"]
}>

export type UserIdArgs = {
};

export type UserEmailArgs = {
};

export type UserBirthdayArgs = {
};

export type QueryUserArgs = {
};