type Movie {
	id: ID!
	title: String!
	year: Int!
	rating: Float
	slug: String
	genre: String
}

input MovieWhereUniqueInput @constraints(minFields: 1, maxFields: 1) {
	id: ID
	title: String
}

type Query {
	movie(where: MovieWhereUniqueInput!): Movie
}

input CreateMovieInput {
	title: String! @trim @validString(minLength: 1, maxLength: 200)
	year: Int! @validInt(min: 1888, max: 2100)
	rating: Float @validFloat(min: 0, max: 10)
	slug: String @lower
	genre: String @upper
}

type Mutation {
	createMovie(input: CreateMovieInput!): Movie!
}
