import { relative, resolve } from 'node:path';
import { createPluginV1, FileBlock, micromatch } from '@baeta/generator-sdk';
import { posixPath } from '@baeta/util-path';

/**
 * Configuration options for the gitignore plugin.
 */
export interface GitignoreOptions {
	/**
	 * Array of file tags to exclude from .gitignore.
	 * File tags are identifiers assigned to generated files
	 * to categorize them by their plugin or purpose.
	 */
	skipTags?: string[];

	/**
	 * Array of files to exclude from .gitignore.
	 */
	skipFilesGlobs?: string[];
}

const defaultSkipTags = ['cloudflare'];

/**
 * A plugin that adds .gitignore entries for generated files.
 *
 * @param options - Plugin configuration options
 * @returns A Baeta generator plugin
 */
export function gitignorePlugin(options?: GitignoreOptions) {
	return createPluginV1({
		name: 'gitignore-plugin',
		actionName: 'add  generated files to .gitignore',
		generate: async (ctx, next) => {
			await next();

			const modulesDir = ctx.generatorOptions.modulesDir;
			const moduleDefinitionName = ctx.generatorOptions.moduleDefinitionName;

			const skippedTags = new Set([...(options?.skipTags ?? []), ...defaultSkipTags]);
			const skippedFilesGlobs = options?.skipFilesGlobs ?? [];

			const toRelativePosix = (absolute: string) => {
				return posixPath(relative(ctx.generatorOptions.cwd, absolute));
			};

			const filePaths = ctx.fileManager.files
				.filter((file) => {
					const relativePath = toRelativePosix(file.filename);
					return (
						!file.filename.endsWith(moduleDefinitionName) &&
						!skippedTags.has(file.tag) &&
						!skippedFilesGlobs.some((glob) => micromatch.isMatch(relativePath, glob)) &&
						file.options?.disableOverwrite !== true
					);
				})
				.map((file) => file.filename);

			const generatedPaths = filePaths
				.map(toRelativePosix)
				.filter((file) => !file.endsWith(moduleDefinitionName));

			const modulesDirRelativePosix = toRelativePosix(modulesDir);
			const moduleDefinitionGlob = `${modulesDirRelativePosix}/**/${moduleDefinitionName}`;

			if (!skippedFilesGlobs.some((glob) => micromatch.isMatch(moduleDefinitionGlob, glob))) {
				generatedPaths.push(moduleDefinitionGlob);
			}

			generatedPaths.sort((a, b) => a.localeCompare(b));

			const gitignoreStart = '# Generated by Baeta - Begin';
			const gitignoreInner = generatedPaths.join('\n');
			const gitignoreEnd = '# Generated by Baeta - End';

			const file = new FileBlock(
				resolve(ctx.generatorOptions.cwd, '.gitignore'),
				gitignoreInner,
				gitignoreStart,
				gitignoreEnd,
				'gitignore',
			);

			ctx.fileManager.add(file);
		},
	});
}
