/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */

import * as Types from "../../__generated__/types";
import type { DocumentNode } from "graphql";
import * as Baeta from "@baeta/core/sdk";


export namespace ModuleMetadata {
  export const id = 'scalars';
  export const dirname = './scalars';
  export const hashes = {};
  export const typedef = {"kind":"Document","definitions":[{"kind":"ScalarTypeDefinition","name":{"kind":"Name","value":"DateTime","loc":{"start":7,"end":15}},"directives":[],"loc":{"start":0,"end":15}}]} as unknown as DocumentNode;
  
  export function createManager(module: Baeta.ModuleBuilder) {
    return {
      ...module.createModuleMethods<Types.ContextType>(),
      Scalar: {
        DateTime: module.createScalarBuilder("DateTime"),
      },
    };
  }
}

export const createScalarsModule = () => Baeta.createModuleManager(ModuleMetadata);
export const getScalarsModule = Baeta.createSingletonModule(createScalarsModule);
