type Movie {
	id: ID!
	title: String!
	year: Int!
	rating: Float
	reviews: [Review!]!
}

type Review {
	id: ID!
	score: Int!
	comment: String!
}

input MovieWhereUniqueInput {
	id: ID!
}

input CreateMovieInput {
	title: String!
	year: Int!
	rating: Float
}

type Query {
	movie(where: MovieWhereUniqueInput!): Movie
	publicMovies: [Movie!]
}

type Mutation {
	createMovie(input: CreateMovieInput!): Movie!
}
