/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */

import * as BaetaSdk from "@baeta/core/sdk";
import type * as BaetaGraphql from "graphql";
import type * as BaetaUserTypes from "../types.ts";

const moduleMetadata = {
  id: 'scalars',
  typedef: {"kind":"Document","definitions":[{"kind":"ScalarTypeDefinition","name":{"kind":"Name","value":"DateTime","loc":{"start":7,"end":15}},"directives":[],"loc":{"start":0,"end":15}},{"kind":"ScalarTypeDefinition","name":{"kind":"Name","value":"UUID","loc":{"start":24,"end":28}},"directives":[],"loc":{"start":17,"end":28}}]} as unknown as BaetaGraphql.DocumentNode
}

export interface BaetaModuleTypes {
  Builders: {
  };
  Factories: {
    DateTime: BaetaGraphql.GraphQLScalarType
    UUID: BaetaGraphql.GraphQLScalarType
  };
};



export const ScalarsModule = BaetaSdk.createModuleBuilder<BaetaUserTypes.Ctx, BaetaUserTypes.Info, BaetaModuleTypes['Builders'], BaetaModuleTypes['Factories']>(moduleMetadata.id, moduleMetadata.typedef, {}, {});