/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */

import { getBaetaDirectivesModule } from "./typedef";

import "./directives.baeta";

export const baetaDirectivesModule = getBaetaDirectivesModule();
