/* This file was generated by baeta. Do not edit it directly. */

/* eslint-disable */

import { registerDirectives } from '@baeta/directives';

import { getBaetaDirectivesModule } from './typedef';

registerDirectives(getBaetaDirectivesModule());
