/* This file was generated by baeta. Do not edit it directly. */

/* eslint-disable */
/* prettier-ignore */

import { registerDirectives } from "@baeta/directives";
import { getBaetaDirectivesModule } from './typedef';

export const baetaDirectivesModule = getBaetaDirectivesModule();

registerDirectives(baetaDirectivesModule);
