/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import * as BaetaUtility from "./utility.ts";
import * as BaetaOverrides from "../modules/types.ts";

export type Scalars = BaetaOverrides.Scalars;

export type Query = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Query"], {
  media: Array<Media>
}>

export type Comic = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Comic"], {
  id: Scalars["ID"]
  title: Scalars["String"]
  year: Scalars["Int"]
  artist: Scalars["String"]
  pages: Scalars["Int"]
}>

export type Movie = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Movie"], {
  id: Scalars["ID"]
  title: Scalars["String"]
  year: Scalars["Int"]
}>

export type TVShow = BaetaUtility.Or<BaetaOverrides.ObjectTypes["TVShow"], {
  id: Scalars["ID"]
  title: Scalars["String"]
  year: Scalars["Int"]
  seasons: Scalars["Int"]
}>

export type Book = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Book"], {
  id: Scalars["ID"]
  title: Scalars["String"]
  year: Scalars["Int"]
  author: Scalars["String"]
  pages: Scalars["Int"]
}>

export type ComicIdArgs = {
};

export type ComicTitleArgs = {
};

export type ComicYearArgs = {
};

export type ComicArtistArgs = {
};

export type ComicPagesArgs = {
};

export type MovieIdArgs = {
};

export type MovieTitleArgs = {
};

export type MovieYearArgs = {
};

export type TVShowIdArgs = {
};

export type TVShowTitleArgs = {
};

export type TVShowYearArgs = {
};

export type TVShowSeasonsArgs = {
};

export type BookIdArgs = {
};

export type BookTitleArgs = {
};

export type BookYearArgs = {
};

export type BookAuthorArgs = {
};

export type BookPagesArgs = {
};

export type QueryMediaArgs = {
};

export type Readable = Comic & {__typename: "Comic"} | Book & {__typename: "Book"}

export type Media = Comic & {__typename: "Comic"} | Movie & {__typename: "Movie"} | TVShow & {__typename: "TVShow"} | Book & {__typename: "Book"}