/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */
/* biome-ignore-all lint: generated file */

import * as BaetaSdk from "@baeta/core/sdk";
import type * as BaetaGraphql from "graphql";
import type * as BaetaTypes from "../../__generated__/types.ts";
import type * as BaetaUserTypes from "../types.ts";

const moduleMetadata = {
  id: 'user-photos',
  typedef: {"kind":"Document","definitions":[{"kind":"ObjectTypeDefinition","name":{"kind":"Name","value":"UserPhoto","loc":{"start":5,"end":14}},"interfaces":[],"directives":[],"fields":[{"kind":"FieldDefinition","name":{"kind":"Name","value":"id","loc":{"start":18,"end":20}},"arguments":[],"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID","loc":{"start":22,"end":24}},"loc":{"start":22,"end":24}},"loc":{"start":22,"end":25}},"directives":[],"loc":{"start":18,"end":25}},{"kind":"FieldDefinition","name":{"kind":"Name","value":"url","loc":{"start":27,"end":30}},"arguments":[],"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String","loc":{"start":32,"end":38}},"loc":{"start":32,"end":38}},"loc":{"start":32,"end":39}},"directives":[],"loc":{"start":27,"end":39}}],"loc":{"start":0,"end":41}},{"kind":"ObjectTypeExtension","name":{"kind":"Name","value":"User","loc":{"start":55,"end":59}},"interfaces":[],"directives":[],"fields":[{"kind":"FieldDefinition","name":{"kind":"Name","value":"photos","loc":{"start":63,"end":69}},"arguments":[],"type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UserPhoto","loc":{"start":72,"end":81}},"loc":{"start":72,"end":81}},"loc":{"start":72,"end":82}},"loc":{"start":71,"end":83}},"directives":[],"loc":{"start":63,"end":83}}],"loc":{"start":43,"end":85}}]} as unknown as BaetaGraphql.DocumentNode
}

export interface BaetaModuleTypes {
  Builders: {
    UserPhoto: BaetaSdk.TypeMethods<BaetaTypes.UserPhoto, BaetaUserTypes.Ctx, BaetaUserTypes.Info, BaetaModuleObjectTypeFields['UserPhoto']['Builder'], BaetaModuleObjectTypeFields['UserPhoto']['Factory']>
    User: BaetaSdk.TypeMethods<BaetaTypes.User, BaetaUserTypes.Ctx, BaetaUserTypes.Info, BaetaModuleObjectTypeFields['User']['Builder'], BaetaModuleObjectTypeFields['User']['Factory']>
  };
  Factories: {
    UserPhoto: BaetaSdk.TypeCompilerFactory<BaetaTypes.UserPhoto, BaetaUserTypes.Ctx, BaetaUserTypes.Info, BaetaModuleObjectTypeFields['UserPhoto']['Factory']>
    User: BaetaSdk.TypeCompilerFactory<BaetaTypes.User, BaetaUserTypes.Ctx, BaetaUserTypes.Info, BaetaModuleObjectTypeFields['User']['Factory']>
  };
};

interface BaetaModuleObjectTypeFields {
  UserPhoto: {
    Builder: {
      id: BaetaSdk.FieldMethods<BaetaTypes.Scalars["ID"], BaetaTypes.UserPhoto, BaetaUserTypes.Ctx, {}, BaetaUserTypes.Info>
      url: BaetaSdk.FieldMethods<BaetaTypes.Scalars["String"], BaetaTypes.UserPhoto, BaetaUserTypes.Ctx, {}, BaetaUserTypes.Info>
    };
    Factory: {
      id: BaetaSdk.Field<BaetaTypes.Scalars["ID"], BaetaTypes.Scalars["ID"], BaetaTypes.UserPhoto, BaetaUserTypes.Ctx, {}, BaetaUserTypes.Info>
      url: BaetaSdk.Field<BaetaTypes.Scalars["String"], BaetaTypes.Scalars["String"], BaetaTypes.UserPhoto, BaetaUserTypes.Ctx, {}, BaetaUserTypes.Info>
    };
  };
  User: {
    Builder: {
      photos: BaetaSdk.FieldMethods<Array<BaetaTypes.UserPhoto> | null, BaetaTypes.User, BaetaUserTypes.Ctx, {}, BaetaUserTypes.Info>
    };
    Factory: {
      photos: BaetaSdk.Field<Array<BaetaTypes.UserPhoto> | null, Array<BaetaTypes.UserPhoto> | null, BaetaTypes.User, BaetaUserTypes.Ctx, {}, BaetaUserTypes.Info>
    };
  };
};

export const UserPhotosModule = BaetaSdk.createModuleBuilder<BaetaUserTypes.Ctx, BaetaUserTypes.Info, BaetaModuleTypes['Builders'], BaetaModuleTypes['Factories']>(moduleMetadata.id, moduleMetadata.typedef, {
  UserPhoto: BaetaSdk.createTypeBuilder("UserPhoto", {
    id: BaetaSdk.createFieldBuilder("UserPhoto", "id"),
    url: BaetaSdk.createFieldBuilder("UserPhoto", "url")
  }),
  User: BaetaSdk.createTypeBuilder("User", {
    photos: BaetaSdk.createFieldBuilder("User", "photos")
  })
}, {

});