/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import { registerDirectives } from "@baeta/directives";

import { getBaetaDirectivesModule } from "./typedef.ts";

registerDirectives(getBaetaDirectivesModule());
