/* This file was generated by baeta. Do not edit it directly. */

/* eslint-disable */
/* prettier-ignore */

import type { Context as ContextType } from '../types/context';
export type Maybe<T> = T | null;
export type InputMaybe<T> = T | undefined;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type { ContextType }
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type User = {
  __typename?: 'User';
  id: Scalars['ID'];
  name: Scalars['String'];
  birthday?: Maybe<Scalars['String']>;
};

export type UserWhereUnique = {
  id?: InputMaybe<Scalars['ID']>;
  email?: InputMaybe<Scalars['String']>;
};

export type UserUpdateInput = {
  name?: InputMaybe<Scalars['String']>;
  birthday?: InputMaybe<Scalars['String']>;
};

export type Query = {
  __typename?: 'Query';
  user?: Maybe<User>;
};


export type QueryUserArgs = {
  where?: InputMaybe<UserWhereUnique>;
};

export type Mutation = {
  __typename?: 'Mutation';
  updateUser?: Maybe<User>;
};


export type MutationUpdateUserArgs = {
  where?: InputMaybe<UserWhereUnique>;
  data?: InputMaybe<UserUpdateInput>;
};

export type Subscription = {
  __typename?: 'Subscription';
  onUserUpdate?: Maybe<User>;
};
