/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import * as BaetaUtility from "./utility.ts";
import * as BaetaOverrides from "../modules/types.ts";

export type Scalars = BaetaOverrides.Scalars;

export type Query = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Query"], {
  user: User | null
  users: Array<User> | null
}>

export type Mutation = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Mutation"], {
  updateUser: User | null
}>

export type Subscription = BaetaUtility.Or<BaetaOverrides.ObjectTypes["Subscription"], {
  userUpdated: User | null
}>

export type UserPhoto = BaetaUtility.Or<BaetaOverrides.ObjectTypes["UserPhoto"], {
  id: Scalars["ID"]
  userId: Scalars["ID"]
  url: Scalars["String"]
}>

export type User = BaetaUtility.Or<BaetaOverrides.ObjectTypes["User"], {
  id: Scalars["ID"]
  email: Scalars["String"]
  lastName: Scalars["String"]
  profile: Scalars["String"] | null
  givenName: Scalars["String"] | null
}>

export type UserPhotoIdArgs = {
};

export type UserPhotoUserIdArgs = {
};

export type UserPhotoUrlArgs = {
};

export type UserPhotosArgs = {
};

export type UserIdArgs = {
};

export type UserEmailArgs = {
};

export type UserLastNameArgs = {
};

export type UserProfileArgs = {
};

export type UserGivenNameArgs = {
};

export type QueryUserArgs = {
  where: UserWhereUniqueInput
};

export type QueryUsersArgs = {
};

export type MutationUpdateUserArgs = {
  where: UserWhereUniqueInput
  data: UserUpdateInput
};

export type SubscriptionUserUpdatedArgs = {
};

export type UserWhereUniqueInput = {
  id: Scalars["ID"]
};

export type UserUpdateInput = {
  lastName: Scalars["String"] | null
  profile: Scalars["String"] | null
  givenName: Scalars["String"] | null
};