/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */

import "./scalars/scalars.resolvers";

import "./user/user.resolvers";

import {getScalarsModule} from "./scalars/typedef";

import {getUserModule} from "./user/typedef";

export const modules = [getScalarsModule(), getUserModule()];
