/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import "./scalars/scalars.resolvers.ts";

import "./user/user.resolvers.ts";

import {getScalarsModule} from "./scalars/typedef.ts";

import {getUserModule} from "./user/typedef.ts";

export const modules = [getScalarsModule(), getUserModule()];
