/* This file was generated by Baeta. Do not edit it directly. All changes will be overwritten by the generator. */
/* eslint-disable */
/* @biome-ignore-all: generated file */

import scalars from "./scalars/index.ts"
import user from "./user/index.ts"

export default [scalars, user];