/* This file was generated by baeta. Do not edit it directly. */

/* eslint-disable */
/* prettier-ignore */

import { getBaetaPaginationModule } from "./typedef";

export const baetaPaginationModule = getBaetaPaginationModule();
