/**
 * Register your reference resolvers for federation entities in this file.
 * This file is generated by Baeta, but it will not be overwritten once created,
 * so it's safe to edit it directly.
 */

import type { EntityHandlerMap } from '../../types-gen/federation.ts';

const entityHandlersMap: EntityHandlerMap = {};

export default entityHandlersMap;
