name: Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: dotansimha/changesets-action@069996e9be15531bd598272996fa23853d61590e #v1.5.2
        with:
          publish: yarn builder release --ci --dry-run
          version: yarn changeset version
          commit: "chore: publish packages"
          title: "chore: publish packages"
          createGithubReleases: aggregate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
