name: Snapshot

on:
  issue_comment:
    types:
      - created

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Snapshot Release
    if: |
      github.event.issue.pull_request &&
      (github.event.comment.body == '/snapit' || github.event.comment.body == '/snapshot-release')
    runs-on: ubuntu-latest
    steps:
      - name: Enforce permission requirement
        uses: prince-chrismc/check-actor-permissions-action@v1
        with:
          permission: write

      - name: Add initial reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes

      - name: Validate pull request
        uses: actions/github-script@v6
        id: pr_data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            try {
              const pullRequest = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              })
              
              // Pull request from fork
              if (context.payload.repository.full_name !== pullRequest.data.head.repo.full_name) {
                const errorMessage = '`/snapit` is not supported on pull requests from forked repositories.'

                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: errorMessage,
                })

                core.setFailed(errorMessage)
              }
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Checkout Repo
        uses: actions/checkout@v3

      # issue_comment requires us to checkout the branch
      # https://github.com/actions/checkout/issues/331#issuecomment-1120113003
      - name: Checkout pull request branch
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Publish Snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn changeset version --snapshot ${{ github.event.issue.number }}

          if [[ `git status --porcelain` ]]; then
              echo "Changes detected, publishing snapshot"
          else
              echo "::error::No changesets detected, skipping snapshot"
              exit 1
          fi

          yarn release:snapshot

      - name: Add failure reaction
        uses: peter-evans/create-or-update-comment@v2
        if: failure()
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: confused

      - name: Add success reaction
        uses: peter-evans/create-or-update-comment@v2
        if: success()
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
