name: Snapshot

on:
  issue_comment:
    types:
      - created

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Snapshot Release
    if: |
      github.event.issue.pull_request &&
      (github.event.comment.body == '/snapit' || github.event.comment.body == '/snapshot-release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Create Release Snapshot
        uses: "the-guild-org/changesets-snapshot-action@v0.0.1"
        with:
          tag: alpha
          prepareScript: "yarn build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
