name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  types:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        uses: andreisergiu98/baeta/ci/setup@ci/composite

      - name: Run type check
        run: yarn type:check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        uses: andreisergiu98/baeta/ci/setup@ci/composite

      - name: Run tests
        run: yarn test

  lint:
    name: Linting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        uses: andreisergiu98/baeta/ci/setup@ci/composite

      - name: Run linting
        run: yarn linter:check

  prettier:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        uses: andreisergiu98/baeta/ci/setup@ci/composite

      - name: Run prettier
        run: yarn prettier:check

  pkg-constraints:
    name: Package constraints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        uses: andreisergiu98/baeta/ci/setup@ci/composite

      - name: Check package constraints
        run: yarn constraints
