name: Testing

on:
  push:
    branches:
      - main
      - ci/workflows
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --no-immutable
      - name: Run linting
        run: yarn lint
  prettier:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --no-immutable
      - name: Run prettier
        run: yarn prettier:check
